const plugin = require('tailwindcss/plugin');
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    screens: {
      xs: '475px',
      ...defaultTheme.screens,
    },
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        emerald: {
          primary: '#047857',
          'primary-content': '#ffffff',
          secondary: '#B45309',
          'secondary-content': '#ffffff',
          accent: '#0D9488',
          neutral: '#2D3748',
          'neutral-content': '#F7FAFC',
          'base-100': '#FAF8F5',
          'base-200': '#F2EEE7',
          'base-300': '#E4DDD2',
          'base-content': '#1A2421',
          info: '#0284C7',
          success: '#16A34A',
          warning: '#D97706',
          error: '#DC2626',
        },
        midnight: {
          primary: '#10B981',
          'primary-content': '#042F2E',
          secondary: '#F59E0B',
          'secondary-content': '#451A03',
          accent: '#14B8A6',
          neutral: '#1F2937',
          'neutral-content': '#F3F4F6',
          'base-100': '#0D1614',
          'base-200': '#152420',
          'base-300': '#223932',
          'base-content': '#F1F5F4',
          info: '#38BDF8',
          success: '#34D399',
          warning: '#FBBF24',
          error: '#F87171',
        },
        sepia: {
          primary: '#2D6A4F',
          'primary-content': '#FFFFFF',
          secondary: '#B45309',
          'secondary-content': '#FFFFFF',
          accent: '#52796F',
          neutral: '#473C33',
          'neutral-content': '#FFFBF5',
          'base-100': '#F5EFE1',
          'base-200': '#EBE2D0',
          'base-300': '#D8CBB3',
          'base-content': '#2B2319',
          info: '#3B82F6',
          success: '#10B981',
          warning: '#F59E0B',
          error: '#EF4444',
        },
      },
      'lemonade',
      'forest',
      'dim',
      'lofi',
    ],
  },
};
