import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Provider } from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-5`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
