import { Inter,  Noto_Sans_Arabic } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter"
});
const notoArabic = Noto_Sans_Arabic({ 
  subsets: ["arabic"],
  variable: "--font-noto-arabic",
  weight: ["300", "400"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="lemonade">
      <body className={`${inter.className} ${notoArabic.variable} m-0 p-5`}>
        {children}
      </body>
    </html>
  );
}
